# -*- coding: utf-8 -*-
"""German translations for the Mientha site, keyed by the English source string.
Missing keys fall back to English at build time."""

DE_BY_EN = {
"Automation that truly changes the way enterprises operate.": "Automatisierung, die die Arbeitsweise von Unternehmen wirklich verändert.",
"We are an international technology partner. We deliver RPA automation and agentic AI solutions, take over business processes and provide top IT specialists for companies across Europe.": "Wir sind ein internationaler Technologiepartner. Wir implementieren RPA-Automatisierung und agentenbasierte Lösungen (Agentic AI), übernehmen Geschäftsprozesse und stellen erstklassige IT-Spezialisten für Unternehmen in ganz Europa bereit.",
"Book a call": "Gespräch vereinbaren",
"Explore services": "Leistungen entdecken",
"experts": "Experten",
"Our clients in numbers": "Unsere Kunden in Zahlen",
"combined client revenue (2023)": "Gesamtumsatz der Kunden (2023)",
"contract retention rate": "Vertragsbindung",
"years of IT experience": "Jahre IT-Erfahrung",
"European countries": "europäische Länder",
"Trusted by European market leaders — FMCG, consulting and manufacturing.": "Führende Unternehmen des europäischen Marktes vertrauen uns — FMCG, Beratung und Produktion.",
"Authorized Partner": "Autorisierter Partner",
"Process Intelligence Partner": "Process-Intelligence-Partner",
"CRM Partner": "CRM-Partner",
"What we do": "Was wir tun",
"Your processes. Our solutions. Real results.": "Ihre Prozesse. Unsere Lösungen. Echte Ergebnisse.",
"We combine technology, experience and a partnership mindset to deliver solutions that make a real difference.": "Wir verbinden Technologie, Erfahrung und partnerschaftliches Denken, um Lösungen zu liefern, die wirklich einen Unterschied machen.",
"RPA & Agentic AI automation": "RPA- & Agentic-AI-Automatisierung",
"Virtual workers and AI agents perform repetitive tasks, analyse data and optimise processes — without human intervention.": "Virtuelle Mitarbeiter und KI-Agenten erledigen wiederkehrende Aufgaben, analysieren Daten und optimieren Prozesse — ganz ohne menschliches Zutun.",
"Business Process Outsourcing": "Business Process Outsourcing",
"We take full ownership of selected processes — procurement, master data, operations — and continuously improve them.": "Wir übernehmen die volle Verantwortung für ausgewählte Prozesse — Einkauf, Stammdaten, Betrieb — und verbessern sie kontinuierlich.",
"Application Management Services": "Application Management Services",
"Maintenance, support and enhancement of enterprise applications with full transparency and reporting.": "Betrieb, Support und Weiterentwicklung von Unternehmensanwendungen mit voller Transparenz und Reporting.",
"IT experts & talent": "IT-Experten & Recruiting",
"Complete project teams and individual IT and finance specialists, matched to your organisation.": "Komplette Projektteams sowie einzelne IT- und Finanzspezialisten, abgestimmt auf Ihre Organisation.",
"Custom solutions": "Maßgeschneiderte Lösungen",
"Dedicated products and integrations designed around your specific industry and processes.": "Dedizierte Produkte und Integrationen, konzipiert für Ihre Branche und Ihre Prozesse.",
"Automated reporting & KPIs": "Automatische Berichte & KPIs",
"Automated reporting and KPI analytics — less manual work, faster and better decisions.": "Automatisierung von Reporting und KPI-Analysen — weniger manuelle Arbeit, schnellere und bessere Entscheidungen.",
"See all services": "Alle Leistungen ansehen",
"Industries": "Branchen",
"Ready-to-deploy products for specific industries": "Einsatzbereite Produkte für konkrete Branchen",
"We don't start from scratch. We deploy proven solutions tailored to the reality of your sector.": "Wir fangen nicht bei null an. Wir implementieren bewährte Lösungen, abgestimmt auf die Realität Ihrer Branche.",
"Flagship": "Flaggschiff",
"Transport & logistics — automated driver settlement": "Transport & Spedition — automatische Fahrerabrechnung",
"A complete solution for efficient driver settlement: from data capture to ready payroll and reports.": "Eine Komplettlösung für die effiziente Fahrerabrechnung: von der Datenerfassung bis zu fertigen Lohnabrechnungen und Berichten.",
"View": "Ansehen",
"FMCG & retail": "FMCG & Handel",
"Invoice, supplier-data and reporting automation.": "Automatisierung von Rechnungen, Lieferantendaten und Reporting.",
"Manufacturing": "Produktion",
"Operational and procurement process optimisation.": "Optimierung von Betriebs- und Einkaufsprozessen.",
"Finance & shared services": "Finanzen & Shared Services",
"P2P/O2C processes, master data, compliance.": "P2P/O2C-Prozesse, Stammdaten, Compliance.",
"All industries": "Alle Branchen",
"Why Mientha": "Warum Mientha",
"A partner, not just a vendor": "Ein Partner, nicht nur ein Lieferant",
"Over 120 experts, experience with market leaders and a delivery model focused on outcomes.": "Über 120 Experten, Erfahrung mit Marktführern und ein auf Ergebnisse ausgerichtetes Liefermodell.",
"Return on investment in as little as 3 months from an automation rollout.": "Return on Investment in nur 3 Monaten nach dem Automatisierungs-Rollout.",
"Up to 80% reduction in operational costs and manual work.": "Bis zu 80 % weniger Betriebskosten und manuelle Arbeit.",
"Blended teams — juniors and seniors combined in the most effective setup.": "Blended Teams — Junioren und Senioren in der effektivsten Konstellation.",
"Best-offer guarantee — more cost-effective than your current provider.": "Best-Offer-Garantie — kosteneffizienter als Ihr aktueller Anbieter.",
"About the company": "Unternehmen kennenlernen",
"“Mientha’s consultants are among the very best — highly skilled, professional and immediately effective. They’ve played a key role in driving our success.”": "„Die Berater von Mientha gehören zu den absolut Besten — hochqualifiziert, professionell und vom ersten Tag an wirksam. Sie haben eine Schlüsselrolle für unseren Erfolg gespielt.“",
"FMCG-sector client": "Kunde aus dem FMCG-Sektor",
"International reach": "Internationale Reichweite",
"One partner. All of Europe.": "Ein Partner. Ganz Europa.",
"Our international team operates across many European countries, delivering IT specialists from a wide range of fields wherever they're needed.": "Unser internationales Team ist in vielen europäischen Ländern tätig und stellt IT-Spezialisten unterschiedlicher Fachrichtungen dort bereit, wo sie gebraucht werden.",
"Let's start": "Legen wir los",
"Let's talk about your next process to automate": "Sprechen wir über Ihren nächsten Prozess zur Automatisierung",
"A free consultation and an initial assessment of savings potential.": "Kostenlose Beratung und eine erste Einschätzung des Einsparpotenzials.",
"Home": "Start",
"Services": "Leistungen",
"Our services": "Unsere Leistungen",
"End-to-end support — from automation to expert teams": "Umfassende Unterstützung — von der Automatisierung bis zu Expertenteams",
"We specialise in process automation (RPA), agentic solutions and high-quality outsourcing. For every service we commit to an offer more cost-effective than your current provider — with no compromise on quality.": "Wir sind spezialisiert auf Prozessautomatisierung (RPA), agentenbasierte Lösungen und hochwertiges Outsourcing. Für jede Leistung verpflichten wir uns zu einem Angebot, das kosteneffizienter ist als Ihr aktueller Anbieter — ohne Kompromisse bei der Qualität.",
"Return on investment in as little as 3 months": "Return on Investment in nur 3 Monaten",
"Up to 80% reduction in operational costs and manual work": "Bis zu 80 % weniger Betriebskosten und manuelle Arbeit",
"Fewer errors, greater control and transparency": "Weniger Fehler, mehr Kontrolle und Transparenz",
"Execution of tasks previously delayed due to lack of resources": "Erledigung von Aufgaben, die bisher mangels Ressourcen liegen blieben",
"We implement advanced automation on leading platforms (UiPath) and AI. Software robots and AI agents independently perform repetitive tasks, analyse data and optimise operational processes.": "Wir implementieren fortschrittliche Automatisierung auf führenden Plattformen (UiPath) und mit künstlicher Intelligenz. Software-Roboter und KI-Agenten erledigen eigenständig wiederkehrende Aufgaben, analysieren Daten und optimieren operative Prozesse.",
"End-to-end procurement support — from order to payment": "End-to-End-Unterstützung des Einkaufsprozesses — von der Bestellung bis zur Zahlung",
"Professional management of supplier data and bank-account records": "Professionelle Verwaltung von Lieferanten- und Bankkontodaten",
"Significant cost reduction with improved service quality": "Deutliche Kostensenkung bei höherer Servicequalität",
"Regular reporting and full transparency of all activities": "Regelmäßiges Reporting und volle Transparenz aller Aktivitäten",
"Business Process Outsourcing (BPO)": "Business Process Outsourcing (BPO)",
"We take full ownership of selected business processes while continuously optimising them. Our expertise lies in operational processes, procurement and master-data management.": "Wir übernehmen die volle Verantwortung für ausgewählte Geschäftsprozesse und optimieren sie zugleich kontinuierlich. Unsere Expertise liegt in operativen Prozessen, im Einkauf und im Stammdatenmanagement.",
"Incident & change management, monitoring, user support": "Incident- & Change-Management, Monitoring, Anwenderunterstützung",
"We free your IT team to focus on strategic initiatives": "Wir entlasten Ihr IT-Team für strategische Aufgaben",
"Regular reporting and full transparency of the collaboration": "Regelmäßiges Reporting und volle Transparenz der Zusammenarbeit",
"Application Management Services (AMS)": "Application Management Services (AMS)",
"We provide ongoing support, maintenance and optimisation of enterprise applications — ensuring performance, stability and alignment with evolving business needs.": "Wir bieten laufenden Support, Betrieb und Optimierung von Unternehmensanwendungen — für Performance, Stabilität und Ausrichtung an sich ändernden Geschäftsanforderungen.",
"Quality guarantee — 90% of candidates hired after the first interview": "Qualitätsgarantie — 90 % der Kandidaten werden nach dem ersten Gespräch eingestellt",
"Blended teams — juniors and seniors in the most effective setup": "Blended Teams — Junioren und Senioren in der effektivsten Konstellation",
"Lower costs — up to 30% below standard market rates": "Niedrigere Kosten — bis zu 30 % günstiger als marktübliche Sätze",
"We provide complete project teams and individual IT and finance specialists — perfectly matched to your organisation's needs.": "Wir stellen komplette Projektteams sowie einzelne IT- und Finanzspezialisten bereit — perfekt abgestimmt auf den Bedarf Ihrer Organisation.",
"Automated reports and KPI analytics — faster decision-making": "Automatische Berichte und KPI-Analysen — schnellere Entscheidungen",
"Improved operational efficiency and process transparency": "Höhere operative Effizienz und Prozesstransparenz",
"Easier planning and better control": "Einfachere Planung und bessere Kontrolle",
"Custom solutions built around your business": "Maßgeschneiderte Lösungen für Ihr Unternehmen",
"We create dedicated solutions tailored to your organisation and industry — including automated reports and KPI analytics that save time and speed up decisions.": "Wir entwickeln dedizierte Lösungen, abgestimmt auf Ihre Organisation und Branche — einschließlich automatischer Berichte und KPI-Analysen, die Zeit sparen und Entscheidungen beschleunigen.",
"Featured service": "Hervorgehobene Leistung",
"24/7 support for business-critical applications": "24/7-Support für geschäftskritische Anwendungen",
"Round-the-clock support and dedicated teams for factories and companies of any industry — with managed knowledge transfer and world-class standards (ITIL 4, ISO 20000/27001).": "Rund-um-die-Uhr-Support und dedizierte Teams für Fabriken und Unternehmen jeder Branche — mit gesteuertem Wissenstransfer und Weltklasse-Standards (ITIL 4, ISO 20000/27001).",
"Explore the service": "Leistung entdecken",
"The way we work": "Wie wir arbeiten",
"From analysis to measurable results": "Von der Analyse zum messbaren Ergebnis",
"Discovery & assessment": "Analyse & Potenzialbewertung",
"We map the process, identify bottlenecks and estimate savings potential.": "Wir bilden den Prozess ab, identifizieren Engpässe und schätzen das Einsparpotenzial.",
"Solution design": "Lösungsdesign",
"We design the automation architecture or outsourcing model tailored to the process.": "Wir entwerfen die Automatisierungsarchitektur oder das Outsourcing-Modell passend zum Prozess.",
"Implementation": "Umsetzung",
"We build, test and deploy the solution in your environment.": "Wir bauen, testen und starten die Lösung in Ihrer Umgebung.",
"Run & optimise": "Betrieb & Optimierung",
"We monitor, report and continuously improve — with full transparency.": "Wir überwachen, berichten und verbessern kontinuierlich — mit voller Transparenz.",
"Our commitment": "Unser Versprechen",
"The best offer — guaranteed": "Das beste Angebot — garantiert",
"For each of these services we commit to a more cost-effective offer than your current provider — with no compromise on quality.": "Für jede dieser Leistungen verpflichten wir uns zu einem kosteneffizienteren Angebot als Ihr aktueller Anbieter — ohne Kompromisse bei der Qualität.",
"Request a quote": "Angebot anfordern",
"Solutions tailored to the reality of your sector": "Lösungen, abgestimmt auf die Realität Ihrer Branche",
"For each industry we combine ready products we can deploy quickly with solutions built to measure. Below are examples of case studies and ready-to-deploy products.": "Für jede Branche verbinden wir einsatzbereite Produkte, die wir schnell implementieren können, mit maßgeschneiderten Lösungen. Nachfolgend Beispiele für Case Studies und einsatzbereite Produkte.",
"Driver settlement": "Fahrerabrechnung",
"Per-diems & allowances": "Reisekosten & Spesen",
"TMS/ERP integration": "TMS/ERP-Integration",
"View solution": "Lösung ansehen",
"Transport & logistics": "Transport & Spedition",
"Our flagship solution for efficient driver settlement — automated capture of route, fuel and per-diem data, pay calculation and ready-to-use reports and payroll.": "Unsere Flaggschiff-Lösung für die effiziente Fahrerabrechnung — automatische Erfassung von Routen-, Kraftstoff- und Spesendaten, Lohnberechnung sowie fertige Berichte und Lohnabrechnungen.",
"Invoice automation": "Rechnungsautomatisierung",
"Supplier master data": "Lieferantenstammdaten",
"Sales reporting": "Verkaufsberichte",
"See 10+ FMCG case studies": "10+ FMCG-Case-Studies ansehen",
"Automation of high-volume processes: invoice workflows, supplier-data management, sales reporting and reconciliations.": "Automatisierung von Hochvolumen-Prozessen: Rechnungsworkflows, Verwaltung von Lieferantendaten, Verkaufsreporting und Abstimmungen.",
"P2P procurement": "P2P-Einkauf",
"Master data": "Stammdaten",
"AMS": "AMS",
"Optimisation of operational, procurement and master-data processes, plus AMS support for production systems.": "Optimierung von operativen, Einkaufs- und Stammdatenprozessen sowie AMS-Support für Produktionssysteme.",
"P2P / O2C": "P2P / O2C",
"Compliance & control": "Compliance & Kontrolle",
"KPI reporting": "KPI-Reporting",
"Finance & shared services (BSS)": "Finanzen & Shared Service Center (BSS)",
"Automation of P2P/O2C processes, bank-account data management, compliance and control, and automated KPI reporting.": "Automatisierung von P2P/O2C-Prozessen, Verwaltung von Bankkontodaten, Compliance und Kontrolle sowie automatisches KPI-Reporting.",
"Back-office automation": "Back-Office-Automatisierung",
"Application support": "Anwendungssupport",
"IT teams": "IT-Teams",
"Telecom": "Telekommunikation",
"Handling high-volume processes, application support and delivery of specialised IT teams.": "Bearbeitung von Hochvolumen-Prozessen, Anwendungssupport und Bereitstellung spezialisierter IT-Teams.",
"Supply chain": "Lieferkette",
"Finance": "Finanzen",
"IT experts": "IT-Experten",
"Automotive": "Automotive",
"Solutions that automate supply-chain and finance processes, plus experts supporting digital transformation.": "Lösungen zur Automatisierung von Prozessen in Lieferkette und Finanzen sowie Experten zur Unterstützung der digitalen Transformation.",
"Don't see your industry?": "Ihre Branche ist nicht dabei?",
"We'll build a solution from the ground up": "Wir entwickeln eine Lösung von Grund auf",
"We create dedicated solutions tailored to your organisation and sector. Let's start with a short conversation about the process you'd like to improve.": "Wir entwickeln dedizierte Lösungen, abgestimmt auf Ihre Organisation und Branche. Beginnen wir mit einem kurzen Gespräch über den Prozess, den Sie verbessern möchten.",
"Let's talk": "Sprechen wir",
"client revenue (2023)": "Kundenumsatz (2023)",
"Flagship product · Transport & logistics": "Flaggschiff-Produkt · Transport & Spedition",
"Automated driver settlement": "Automatische Fahrerabrechnung",
"No more manual document collection and spreadsheets. Our solution automates the entire driver-settlement process — from data capture, through pay and per-diem calculation, to ready reports and payroll export.": "Schluss mit manueller Dokumentensammlung und Tabellen. Unsere Lösung automatisiert den gesamten Prozess der Fahrerabrechnung — von der Datenerfassung über die Berechnung von Löhnen und Spesen bis hin zu fertigen Berichten und dem Export ins Lohnsystem.",
"Request a demo": "Demo anfragen",
"See the results": "Ergebnisse ansehen",
"The challenge": "Die Herausforderung",
"Driver settlement eats time and generates errors": "Die Fahrerabrechnung kostet Zeit und erzeugt Fehler",
"In transport and forwarding companies, settling drivers is a monthly effort: data from route cards, fuel, per-diems and telematics has to be collected, reconciled and calculated by hand against complex rules. That means delays, mistakes and frustration.": "In Transport- und Speditionsunternehmen ist die Fahrerabrechnung eine monatliche Kraftanstrengung: Daten aus Fahrtenkarten, Tankvorgängen, Spesen und Telematiksystemen müssen manuell gesammelt, abgeglichen und nach komplexen Regeln berechnet werden. Das bedeutet Verzögerungen, Fehler und Frust.",
"Data scattered across many systems and documents": "Daten verteilt über viele Systeme und Dokumente",
"Manual calculation of domestic and international per-diems": "Manuelle Berechnung von in- und ausländischen Spesen",
"Errors and corrections that undermine driver trust": "Fehler und Korrekturen, die das Vertrauen der Fahrer untergraben",
"No transparency and hard-to-audit settlements": "Fehlende Transparenz und schwer prüfbare Abrechnungen",
"How it works": "So funktioniert es",
"The whole settlement process — automated": "Der gesamte Abrechnungsprozess — automatisch",
"Data capture": "Datenerfassung",
"A robot collects data from telematics, fuel cards, TMS and route documents — automatically, on schedule.": "Ein Roboter sammelt Daten aus Telematik, Tankkarten, TMS und Routendokumenten — automatisch und zeitgesteuert.",
"Validation & reconciliation": "Validierung & Abgleich",
"The system checks completeness, flags gaps and reconciles routes with fuel and working time.": "Das System prüft die Vollständigkeit der Daten, erkennt Lücken und gleicht Routen mit Tankvorgängen und Arbeitszeiten ab.",
"Pay & per-diem calculation": "Lohn- & Spesenberechnung",
"Pay rules, domestic and foreign per-diems and bonuses are calculated automatically, per your policy.": "Lohnregeln, in- und ausländische Spesen sowie Zulagen werden automatisch nach Ihren Vorgaben berechnet.",
"Reports & export": "Berichte & Export",
"Finished settlements flow into reports, driver panels and export to payroll/ERP.": "Fertige Abrechnungen fließen in Berichte, Fahrer-Panels und den Export ins Lohnsystem/ERP.",
"Time savings": "Zeitersparnis",
"Monthly settlement cut from days to hours by automating data capture and calculation.": "Verkürzung der monatlichen Abrechnung von Tagen auf Stunden durch automatisierte Datenerfassung und Berechnung.",
"Fewer errors": "Weniger Fehler",
"Consistent rules and validation eliminate mistakes and costly corrections.": "Einheitliche Regeln und Validierung eliminieren Fehler und kostspielige Korrekturen.",
"Full transparency": "Volle Transparenz",
"Every settlement is auditable and drivers see their data in a clear panel.": "Jede Abrechnung ist prüfbar, und Fahrer sehen ihre Daten in einem übersichtlichen Panel.",
"Integrations": "Integrationen",
"We connect to popular TMS, telematics, fuel cards and payroll/ERP systems.": "Wir verbinden uns mit gängigen TMS, Telematik, Tankkarten und Lohn-/ERP-Systemen.",
"Compliance": "Compliance",
"Per-diem and working-time rules aligned with national and international regulations.": "Spesen- und Arbeitszeitregeln im Einklang mit nationalen und internationalen Vorschriften.",
"No-cold-start rollout": "Rollout ohne Kaltstart",
"We start from a ready product and tune it to your rules — fast go-live.": "Wir starten mit einem fertigen Produkt und passen es an Ihre Regeln an — schneller Go-live.",
"Potential impact": "Möglicher Effekt",
"Results you can expect": "Ergebnisse, die Sie erwarten können",
"less manual settlement work": "weniger manuelle Abrechnungsarbeit",
"mo": "Mon.",
"typical return on investment": "typischer Return on Investment",
"errors": "Fehler",
"thanks to consistent rules": "dank einheitlicher Regeln",
"automated data capture": "automatische Datenerfassung",
"Indicative figures, depending on fleet size and process configuration.": "Richtwerte, abhängig von Flottengröße und Prozesskonfiguration.",
"Request a driver-settlement demo": "Demo der Fahrerabrechnung anfragen",
"Case studies": "Case Studies",
"The results we deliver for clients": "Ergebnisse, die wir für Kunden liefern",
"Selected examples of automation, outsourcing and expert-team engagements. For confidentiality, some client details have been anonymised.": "Ausgewählte Beispiele für Automatisierung, Outsourcing und Expertenteams. Aus Vertraulichkeitsgründen wurden einige Kundendaten anonymisiert.",
"Collection · FMCG": "Sammlung · FMCG",
"10+ automations for the FMCG industry": "10+ Automatisierungen für die FMCG-Branche",
"VAT settlements, receivables and credit, P2P queries, treasury and HR — see the full set of case studies, explained step by step.": "MwSt-Abrechnungen, Forderungen und Kredit, P2P-Anfragen, Treasury und HR — sehen Sie sich die komplette Sammlung Schritt für Schritt erklärter Case Studies an.",
"View collection": "Sammlung ansehen",
"View details": "Details ansehen",
"Deployment of our ready driver-settlement product at a fleet operator — automating data capture, per-diem calculation and payroll export.": "Einführung unseres fertigen Produkts zur Fahrerabrechnung bei einem Flottenbetreiber — Automatisierung von Datenerfassung, Spesenberechnung und Export ins Lohnsystem.",
"-80%": "-80 %",
"settlement time": "Abrechnungszeit",
"FMCG": "FMCG",
"Invoice-processing automation": "Automatisierung des Rechnungsworkflows",
"RPA robots took over purchase-invoice registration and coding at an FMCG manufacturer, integrating with SAP and removing manual work.": "RPA-Roboter übernahmen die Erfassung und Kontierung von Eingangsrechnungen bei einem FMCG-Hersteller, integrierten sich in SAP und eliminierten manuelle Arbeit.",
"3 mo": "3 Mon.",
"to return on investment": "bis zum Return on Investment",
"Manufacturing · AMS": "Produktion · AMS",
"Enterprise application management": "Betrieb von Unternehmensanwendungen",
"We took over AMS for a manufacturer's core applications, providing monitoring, user support and proactive enhancements.": "Wir übernahmen AMS für die Kernanwendungen eines Herstellers und sorgten für Monitoring, Anwendersupport und proaktive Verbesserungen.",
"90%+": "90 %+",
"engagement retention": "Fortführung der Zusammenarbeit",
"Finance · Talent": "Finanzen · Talent",
"IT expert team for a bank": "IT-Expertenteam für eine Bank",
"We delivered a blended team of IT and finance specialists for a transformation programme, matched to the organisation's needs.": "Wir stellten ein Blended Team aus IT- und Finanzspezialisten für ein Transformationsprogramm bereit, abgestimmt auf den Bedarf der Organisation.",
"90%": "90 %",
"candidates hired after 1st interview": "der Kandidaten nach dem 1. Gespräch eingestellt",
"Procurement · BPO": "Einkauf · BPO",
"Procurement process outsourcing": "Outsourcing des Einkaufsprozesses",
"We took over the end-to-end procurement process and supplier/bank-account data management, lowering costs with higher quality.": "Wir übernahmen den End-to-End-Einkaufsprozess sowie die Verwaltung von Lieferanten- und Bankkontodaten und senkten die Kosten bei höherer Qualität.",
"-30%": "-30 %",
"process cost": "Prozesskosten",
"Agentic AI": "Agentic AI",
"AI agents in data operations": "KI-Agenten im Datenbetrieb",
"Deployment of AI agents for analysing and processing operational data, executing tasks previously delayed due to lack of resources.": "Einsatz von KI-Agenten zur Analyse und Verarbeitung operativer Daten, die bisher mangels Ressourcen liegen gebliebene Aufgaben erledigen.",
"24/7": "24/7",
"uninterrupted operation": "unterbrechungsfreier Betrieb",
"Your process could be next": "Ihr Prozess könnte der nächste sein",
"Tell us about a process you'd like to improve — we'll prepare a potential assessment.": "Erzählen Sie uns von einem Prozess, den Sie verbessern möchten — wir erstellen eine Potenzialbewertung.",
"About us": "Über uns",
"An international partner in automation and IT": "Internationaler Partner für Automatisierung und IT",
"Mientha was founded to genuinely solve the business problems large organisations face. Today it is a team of over 120 experts operating across many European countries.": "Mientha wurde gegründet, um die geschäftlichen Herausforderungen großer Organisationen wirklich zu lösen. Heute ist es ein Team von über 120 Experten, das in vielen Ländern Europas tätig ist.",
"Our story": "Unsere Geschichte",
"From IT experience to a corporate partner": "Von IT-Erfahrung zum Partner für Konzerne",
"The company was founded by a leader with over 20 years of experience in technology and IT, who moved from a technical role into business and IT consulting. That blend of perspectives helped build a company that effectively solves the real problems of corporate clients — today employing over 120 experts.": "Gegründet wurde das Unternehmen von einem Leader mit über 20 Jahren Erfahrung in Technologie und IT, der den Weg von einer technischen Rolle zur Geschäfts- und IT-Beratung ging. Diese Verbindung von Perspektiven ermöglichte den Aufbau eines Unternehmens, das die realen Probleme von Konzernkunden effektiv löst — heute mit über 120 Experten.",
"“We combine technology, experience and a partnership mindset to deliver solutions that truly make a difference.”": "„Wir verbinden Technologie, Erfahrung und partnerschaftliches Denken, um Lösungen zu liefern, die wirklich einen Unterschied machen.“",
"Our clients": "Unsere Kunden",
"We work with European market leaders": "Wir arbeiten mit Marktführern in Europa",
"combined client revenue in 2023": "Gesamtumsatz der Kunden 2023",
"experts in the team": "Experten im Team",
"We work with leading companies across FMCG, consulting and manufacturing. Our international team delivers IT specialists from a wide range of fields across Europe.": "Wir arbeiten mit führenden Unternehmen in den Bereichen FMCG, Beratung und Produktion. Unser internationales Team liefert IT-Spezialisten unterschiedlichster Fachrichtungen in ganz Europa.",
"Technology partnerships": "Technologiepartnerschaften",
"The best technology in experienced hands": "Beste Technologie in erfahrenen Händen",
"We combine leading platforms with the know-how to deploy them well — so automation delivers a real, measurable return.": "Wir verbinden führende Plattformen mit dem Know-how, sie erfolgreich einzuführen — damit Automatisierung einen echten, messbaren Return liefert.",
"We build automations on the leading enterprise RPA platform — ensuring proven, scalable and secure solutions.": "Wir bauen Automatisierungen auf der führenden Enterprise-RPA-Plattform — für bewährte, skalierbare und sichere Lösungen.",
"Deep knowledge of the SAP ecosystem lets us automate and support processes tightly connected to your ERP.": "Tiefe Kenntnis des SAP-Ökosystems ermöglicht es uns, Prozesse eng verzahnt mit Ihrem ERP zu automatisieren und zu unterstützen.",
"KYP.ai is a process & task mining platform that reveals how processes really run in an organisation. Thanks to this partnership we don't guess what to automate — we know it from data.": "KYP.ai ist eine Process- & Task-Mining-Plattform, die zeigt, wie Prozesse in einer Organisation tatsächlich ablaufen. Dank dieser Partnerschaft raten wir nicht, was zu automatisieren ist — wir wissen es auf Basis von Daten.",
"What you gain": "Was Sie davon haben",
"Pinpointing the processes with the biggest potential": "Präzises Aufspüren der Prozesse mit dem größten Potenzial",
"Measuring real savings potential before we build": "Messung des realen Einsparpotenzials vor der Umsetzung",
"Prioritising automations by ROI": "Priorisierung der Automatisierungen nach ROI",
"Continuous measurement of impact and productivity": "Kontinuierliche Messung von Wirkung und Produktivität",
"A faster, more certain return on investment": "Ein schnellerer und sichererer Return on Investment",
"Partner (Solution Provider)": "Partner (Solution Provider)",
"Pipedrive is a sales CRM. As a partner we implement, configure and integrate Pipedrive and automate sales processes — connecting the CRM with your systems and robots.": "Pipedrive ist ein Vertriebs-CRM. Als Partner implementieren, konfigurieren und integrieren wir Pipedrive und automatisieren Vertriebsprozesse — indem wir das CRM mit Ihren Systemen und Robotern verbinden.",
"CRM implementation and configuration for your sales process": "CRM-Einführung und -Konfiguration für Ihren Vertriebsprozess",
"Integrations with SAP, other systems and automation": "Integrationen mit SAP, anderen Systemen und Automatisierung",
"User training and support": "Anwenderschulungen und Support",
"A faster, more predictable sales pipeline": "Eine schnellere und planbarere Vertriebspipeline",
"Our values": "Unsere Werte",
"Outcome-driven": "Ergebnisorientiert",
"We measure success by savings and real process improvement for the client.": "Wir messen Erfolg an Einsparungen und echter Prozessverbesserung beim Kunden.",
"Partnership & transparency": "Partnerschaft & Transparenz",
"Regular reporting and full visibility — we act as part of your team.": "Regelmäßiges Reporting und volle Sichtbarkeit — wir agieren als Teil Ihres Teams.",
"We deliver experts and solutions across many European countries.": "Wir liefern Experten und Lösungen in vielen Ländern Europas.",
"Let's get in touch": "Lernen wir uns kennen",
"Contact": "Kontakt",
"Let's talk about your process": "Sprechen wir über Ihren Prozess",
"Book a free consultation. We'll reply within one business day.": "Vereinbaren Sie eine kostenlose Beratung. Wir antworten innerhalb eines Werktages.",
"Contact details": "Kontaktdaten",
"E-mail": "E-Mail",
"Phone": "Telefon",
"Address": "Adresse",
"Direct contact": "Direkter Kontakt",
"Send us a message": "Schreiben Sie uns",
"Fill in the form — we'll get back to you as soon as possible.": "Füllen Sie das Formular aus — wir melden uns schnellstmöglich zurück.",
"Full name": "Vor- und Nachname",
"Company": "Unternehmen",
"Work e-mail": "Geschäftliche E-Mail",
"What are you interested in?": "Woran sind Sie interessiert?",
"RPA / Agentic AI automation": "RPA- / Agentic-AI-Automatisierung",
"Driver settlement (transport)": "Fahrerabrechnung (Transport)",
"BPO / process outsourcing": "BPO / Prozess-Outsourcing",
"AMS — application management": "AMS — Anwendungsbetrieb",
"IT experts / talent": "IT-Experten / Recruiting",
"Other": "Sonstiges",
"Message": "Nachricht",
"Send message": "Nachricht senden",
"By submitting, you agree to your data being processed for contact purposes.": "Mit dem Absenden stimmen Sie der Verarbeitung Ihrer Daten zur Kontaktaufnahme zu.",
"Thank you!": "Vielen Dank!",
"Your message has been captured. We'll be in touch within one business day.": "Ihre Nachricht wurde erfasst. Wir melden uns innerhalb eines Werktages.",
"(This is a demo form — connect your backend or e-mail service.)": "(Dies ist ein Demo-Formular — binden Sie Ihr Backend oder einen E-Mail-Dienst an.)",
"Automated VAT settlements": "Automatische MwSt-Abrechnungen",
"FMCG · Case study": "FMCG · Case Study",
"No more manually re-typing data between systems and VAT forms.": "Schluss mit dem manuellen Übertragen von Daten zwischen Systemen und MwSt-Formularen.",
"All FMCG case studies": "Alle FMCG-Case-Studies",
"Monthly VAT settlements across many countries meant hours of tedious copying of data into spreadsheets and forms. At that scale, mistakes and late filings are almost inevitable.": "Monatliche MwSt-Abrechnungen in vielen Ländern bedeuteten stundenlanges, mühsames Kopieren von Daten in Tabellen und Formulare. In dieser Größenordnung sind Fehler und verspätete Meldungen kaum vermeidbar.",
"What we did": "Was wir getan haben",
"The solution in practice": "Die Lösung in der Praxis",
"We deployed a “digital worker” that pulls the data itself, prepares calculations per the client’s rules, fills in VAT returns and verifies counterparties, then archives the documents and prepares tax payments for one-click approval.": "Wir setzten einen „digitalen Mitarbeiter“ ein, der die Daten selbst abruft, Berechnungen nach den Regeln des Kunden erstellt, MwSt-Meldungen ausfüllt und Geschäftspartner prüft, dann die Dokumente archiviert und Steuerzahlungen zur Freigabe per Klick vorbereitet.",
"Business benefits": "Geschäftlicher Nutzen",
"Returns ready to file with no manual work": "Meldungen ohne manuelle Arbeit versandfertig",
"Fewer errors and costly corrections": "Weniger Fehler und kostspielige Korrekturen",
"On-time filing and audit peace of mind": "Termintreue und Ruhe bei Audits",
"Easy to scale to more countries and entities": "Einfache Skalierung auf weitere Länder und Gesellschaften",
"Impact on results": "Wirkung auf die Ergebnisse",
"Shorter VAT close": "Kürzerer MwSt-Abschluss",
"Lower risk of tax penalties": "Geringeres Risiko von Steuerstrafen",
"A relieved finance team": "Ein entlastetes Finanzteam",
"24/7 mode": "24/7-Betrieb",
"A similar process slowing your team down?": "Bremst ein ähnlicher Prozess Ihr Team?",
"We'll show how quickly we can automate it for you.": "Wir zeigen Ihnen, wie schnell wir ihn bei Ihnen automatisieren können.",
"Collections cases routed to the right person instantly": "Inkassofälle gehen sofort an die richtige Person",
"Receivables cases reach the right owner instantly — no manual sorting.": "Forderungsfälle erreichen sofort den richtigen Bearbeiter — ohne manuelles Sortieren.",
"Receivables cases had to be assigned by hand to the right people across regions. That delayed the start of collections and caused mistakes.": "Forderungsfälle mussten manuell den richtigen Personen in verschiedenen Regionen zugeordnet werden. Das verzögerte den Inkassostart und führte zu Fehlern.",
"A robot recognises who a case concerns and automatically routes it to the right collections owner or regional team — instantly and around the clock.": "Ein Roboter erkennt, wen ein Fall betrifft, und leitet ihn automatisch an den richtigen Inkassobearbeiter oder das regionale Team weiter — sofort und rund um die Uhr.",
"No more manual case sorting": "Kein manuelles Sortieren von Fällen mehr",
"A faster start to collections": "Ein schnellerer Inkassostart",
"Fewer misroutes and rework": "Weniger Fehlzuordnungen und Nacharbeit",
"One consistent process across countries": "Ein einheitlicher Prozess in allen Ländern",
"Faster cash collection (DSO)": "Schnellerer Zahlungseingang (DSO)",
"Higher team productivity": "Höhere Teamproduktivität",
"Shorter case handling time": "Kürzere Bearbeitungszeit pro Fall",
"Faster release of blocked orders": "Schnellere Freigabe gesperrter Aufträge",
"Valid orders move faster — so the company earns faster.": "Korrekte Aufträge laufen schneller — und das Unternehmen verdient schneller.",
"Orders blocked by credit control waited for manual review. Every hour of delay meant postponed sales and revenue.": "Durch die Kreditkontrolle gesperrte Aufträge warteten auf manuelle Prüfung. Jede Stunde Verzögerung bedeutete aufgeschobenen Umsatz.",
"Every few minutes a robot detects blocked orders, gathers the needed information, runs pre-checks and starts the approval process per the client’s rules — then releases the order once a decision is made.": "Alle paar Minuten erkennt ein Roboter gesperrte Aufträge, sammelt die nötigen Informationen, führt Vorprüfungen durch und startet den Freigabeprozess nach den Regeln des Kunden — und gibt den Auftrag nach der Entscheidung frei.",
"Faster release of valid orders": "Schnellere Freigabe korrekter Aufträge",
"Less manual data checking": "Weniger manuelle Datenprüfung",
"A standardised approval path": "Ein standardisierter Freigabeweg",
"Fewer lost revenues from delays": "Weniger Umsatzverluste durch Verzögerungen",
"Faster revenue realisation": "Schnellere Umsatzrealisierung",
"Shorter cycle time": "Kürzere Durchlaufzeit",
"Better credit-risk control": "Bessere Kontrolle des Kreditrisikos",
"Smooth payment-term changes": "Reibungslose Änderung von Zahlungszielen",
"Customer requests for new payment terms handled quickly and in full control.": "Kundenanträge auf neue Zahlungsziele — schnell und vollständig unter Kontrolle bearbeitet.",
"Handling requests to change payment terms required manual data gathering and chasing approvals.": "Die Bearbeitung von Anträgen auf Änderung des Zahlungsziels erforderte manuelles Sammeln von Daten und das Nachhalten von Freigaben.",
"A robot enriches the case with all the data needed and drives it through the approval process per the client’s rules — all the way to a decision and closure.": "Ein Roboter reichert den Fall mit allen nötigen Daten an und führt ihn nach den Regeln des Kunden durch den Freigabeprozess — bis zur Entscheidung und zum Abschluss.",
"Faster request handling": "Schnellere Antragsbearbeitung",
"Better customer experience and flexibility": "Besseres Kundenerlebnis und Flexibilität",
"Less manual work": "Weniger manuelle Arbeit",
"Better control over cash flow": "Bessere Kontrolle über den Cashflow",
"Better terms management (DSO)": "Besseres Zahlungsziel-Management (DSO)",
"Higher customer satisfaction": "Höhere Kundenzufriedenheit",
"Predictable cash flow": "Planbarer Cashflow",
"Fast, consistent credit decisions": "Schnelle und konsistente Kreditentscheidungen",
"Streamlined credit-limit management — supporting sales without adding risk.": "Effizientes Kreditlimit-Management — Vertriebsunterstützung ohne zusätzliches Risiko.",
"Requests for a current credit limit and applications to increase or decrease it required manual gathering of financial data and waited a long time for a decision.": "Anfragen zum aktuellen Kreditlimit sowie Anträge auf Erhöhung oder Senkung erforderten manuelles Sammeln von Finanzdaten und warteten lange auf eine Entscheidung.",
"A robot automatically retrieves up-to-date client and history data, enriches the case and passes it for decision — handling both simple enquiries and limit-change applications.": "Ein Roboter ruft automatisch aktuelle Kunden- und Verlaufsdaten ab, reichert den Fall an und übergibt ihn zur Entscheidung — für einfache Anfragen ebenso wie für Anträge auf Limitänderung.",
"Faster credit decisions": "Schnellere Kreditentscheidungen",
"Stronger sales support without added risk": "Wirksamere Vertriebsunterstützung ohne mehr Risiko",
"Automated financial-data retrieval": "Automatischer Abruf von Finanzdaten",
"Uniform rules across all markets": "Einheitliche Regeln in allen Märkten",
"Faster client onboarding and revenue": "Schnelleres Kunden-Onboarding und Umsätze",
"Bad-debt risk under control": "Kontrolle des Forderungsausfallrisikos",
"Shorter credit-decision time": "Kürzere Kreditentscheidungszeit",
"Automated P2P query handling": "Automatische Bearbeitung von P2P-Anfragen",
"Invoice copies, statuses and statements delivered instantly — around the clock.": "Rechnungskopien, Status und Übersichten sofort geliefert — rund um die Uhr.",
"Teams and suppliers flooded the finance team with repetitive requests: invoice copies, payment status, account statements. That tied up people and created backlogs.": "Teams und Lieferanten überhäuften die Finanzabteilung mit wiederkehrenden Anfragen: Rechnungskopien, Zahlungsstatus, Kontoauszüge. Das band Mitarbeiter und erzeugte Rückstände.",
"A robot receives the query, finds the needed document or information and sends the answer back to the user — automatically and without interruption, 24/7.": "Ein Roboter nimmt die Anfrage entgegen, findet das benötigte Dokument oder die Information und sendet die Antwort an den Nutzer zurück — automatisch und ohne Unterbrechung, 24/7.",
"Instant answers to common queries": "Sofortige Antworten auf typische Anfragen",
"An end to repetitive manual work": "Ein Ende wiederkehrender manueller Arbeit",
"A service available 24/7": "Ein Service rund um die Uhr (24/7)",
"Smaller backlog in finance teams": "Weniger Rückstau in den Finanzteams",
"Higher productivity": "Höhere Produktivität",
"Lower cost per query": "Niedrigere Kosten pro Anfrage",
"Happier users and suppliers": "Zufriedene Nutzer und Lieferanten",
"Bank-statement monitoring & cash application": "Überwachung von Kontoauszügen & Cash Application",
"Missing statements caught proactively — smooth cash application.": "Fehlende Auszüge werden proaktiv erkannt — reibungslose Verbuchung von Zahlungseingängen.",
"Missing or delayed bank statements could stall cash application and distort the liquidity picture — and were usually spotted too late.": "Fehlende oder verspätete Kontoauszüge konnten die Verbuchung von Zahlungseingängen aufhalten und das Liquiditätsbild verzerren — und wurden meist zu spät bemerkt.",
"A robot analyses reports from the banking system, tells real gaps from non-working days and — when a statement should already be available — automatically raises a ticket and routes it to the right person.": "Ein Roboter analysiert Berichte aus dem Banksystem, unterscheidet echte Lücken von arbeitsfreien Tagen und legt — wenn ein Auszug bereits verfügbar sein sollte — automatisch ein Ticket an und leitet es an die richtige Person weiter.",
"Proactive gap detection": "Proaktives Erkennen von Lücken",
"Faster problem resolution": "Schnellere Problemlösung",
"Continuity of cash application": "Kontinuität der Zahlungsverbuchung",
"Fewer stoppages in finance processes": "Weniger Stillstände in Finanzprozessen",
"Faster cash application (DSO)": "Schnellere Zahlungsverbuchung (DSO)",
"Better cash-flow visibility": "Bessere Sichtbarkeit der Cashflows",
"Lower operational risk": "Geringeres operatives Risiko",
"Automated bank-balance reconciliation": "Automatischer Abgleich von Bankkontosalden",
"Balances always in sync between systems — discrepancies caught at once.": "Salden zwischen Systemen stets im Einklang — Abweichungen sofort erkannt.",
"Manually comparing balances between two banking systems was time-consuming, and discrepancies surfaced too late.": "Der manuelle Abgleich von Salden zwischen zwei Bank-/Treasury-Systemen war zeitaufwendig, und Abweichungen kamen zu spät ans Licht.",
"A robot automatically compares balances for every account and, if there is a difference, raises a ticket and points to the person or team responsible for resolving it.": "Ein Roboter vergleicht automatisch die Salden für jedes Konto und legt bei einer Abweichung ein Ticket an und benennt die verantwortliche Person oder das Team.",
"Automatic balance-consistency checks": "Automatische Prüfung der Saldenübereinstimmung",
"Early detection of differences": "Frühzeitiges Erkennen von Differenzen",
"Fewer financial discrepancies": "Weniger finanzielle Abweichungen",
"Audit readiness": "Audit-Bereitschaft",
"Higher financial-data accuracy": "Höhere Genauigkeit der Finanzdaten",
"Lower audit risk": "Geringeres Audit-Risiko",
"Shorter reconciliation time": "Kürzere Abgleichszeit",
"Employee data mass update": "Massenaktualisierung von Mitarbeiterdaten",
"Hundreds of data changes done quickly, safely and error-free.": "Hunderte Datenänderungen — schnell, sicher und fehlerfrei erledigt.",
"Bulk changes to employee data in the HR system are a tedious, sensitive task where mistakes come easily.": "Massenänderungen von Mitarbeiterdaten im HR-System sind eine mühsame, sensible Aufgabe, bei der Fehler leicht passieren.",
"A robot picks up the request with the change file, verifies its scope (excluding management), prepares the data and performs the bulk update, then reports the result back to HR.": "Ein Roboter nimmt den Antrag mit der Änderungsdatei auf, prüft ihren Umfang (ohne Führungskräfte), bereitet die Daten auf und führt die Massenaktualisierung durch, dann meldet er das Ergebnis an HR zurück.",
"Fast, safe bulk updates": "Schnelle, sichere Massenaktualisierung",
"No manual data-entry errors": "Keine Fehler durch manuelle Eingabe",
"Control over sensitive data": "Kontrolle über sensible Daten",
"Full audit trail and reporting": "Vollständiger Audit-Trail und Reporting",
"Higher HR productivity": "Höhere HR-Produktivität",
"Better data quality": "Bessere Datenqualität",
"Compliance and fewer corrections": "Compliance und weniger Korrekturen",
"Automated new-hire onboarding": "Automatisches Onboarding neuer Mitarbeiter",
"New hires ready to work sooner — less paperwork for HR.": "Neue Mitarbeiter sind schneller einsatzbereit — weniger Papierkram für HR.",
"Creating and updating new-hire records required manual file processing and many steps across systems.": "Das Anlegen und Aktualisieren von Daten neuer Mitarbeiter erforderte manuelle Dateiverarbeitung und viele Schritte zwischen Systemen.",
"A robot retrieves and securely processes data from the payroll system, archives it and creates or updates the employee in the HR system — from new hire, through changes, to offboarding.": "Ein Roboter ruft Daten aus dem Personalsystem sicher ab und verarbeitet sie, archiviert sie und legt den Mitarbeiter im HR-System an oder aktualisiert ihn — von der Neueinstellung über Änderungen bis zum Offboarding.",
"Automated onboarding data flow": "Automatisierter Datenfluss beim Onboarding",
"Faster activation of employees in systems": "Schnellere Aktivierung von Mitarbeitern in den Systemen",
"HR freed from admin work": "HR von Verwaltungsarbeit entlastet",
"Secure data processing": "Sichere Datenverarbeitung",
"Shorter time-to-onboard": "Kürzere Onboarding-Zeit",
"Better employee experience": "Besseres Mitarbeitererlebnis",
"Lower HR operating costs": "Niedrigere operative HR-Kosten",
"Industry · FMCG & retail": "Branche · FMCG & Handel",
"Automation for FMCG leaders": "Automatisierung für FMCG-Marktführer",
"For FMCG companies we have automated more than a dozen finance, credit and HR processes — from VAT settlements to employee onboarding. Below are real examples of our work and the business benefits they delivered.": "Für Unternehmen der FMCG-Branche haben wir mehr als ein Dutzend Finanz-, Kredit- und HR-Prozesse automatisiert — von MwSt-Abrechnungen bis zum Mitarbeiter-Onboarding. Nachfolgend echte Beispiele unserer Arbeit und der erzielte geschäftliche Nutzen.",
"High-volume processes in finance, customer service and HR — where automation delivers the fastest return.": "Hochvolumen-Prozesse in Finanzen, Kundenservice und HR — Bereiche, in denen Automatisierung den schnellsten Return liefert.",
"Finance & receivables": "Finanzen & Forderungen",
"Procurement & payments": "Einkauf & Zahlungen",
"Selected automation deliveries": "Ausgewählte Automatisierungsprojekte",
"We describe each example simply: what the problem was, what we did and what the client gained.": "Jedes Beispiel beschreiben wir einfach: Was das Problem war, was wir getan haben und was der Kunde gewonnen hat.",
"View case study": "Case Study ansehen",
"For confidentiality, client details have been anonymised. Examples based on real deployments.": "Aus Vertraulichkeitsgründen wurden Kundendaten anonymisiert. Beispiele basieren auf realen Projekten.",
"Want similar results in your FMCG business?": "Möchten Sie ähnliche Ergebnisse in Ihrem FMCG-Unternehmen?",
"Let's start with a short talk about the process with the biggest potential.": "Beginnen wir mit einem kurzen Gespräch über den Prozess mit dem größten Potenzial.",
"24/7 support": "24/7-Support",
"Service · Dedicated teams": "Leistung · Dedizierte Teams",
"We provide round-the-clock support (24/7/365) for any business-critical application — in factories and companies of any industry. We build dedicated teams matched to your technologies and take ownership of keeping them running.": "Wir bieten Rund-um-die-Uhr-Support (24/7/365) für jede geschäftskritische Anwendung — in Fabriken und Unternehmen jeder Branche. Wir bauen dedizierte Teams, abgestimmt auf Ihre Technologien, und übernehmen die Verantwortung für den laufenden Betrieb.",
"Talk to us about support": "Über Support sprechen",
"All services": "Alle Leistungen",
"What we offer": "Was wir bieten",
"Uninterrupted care for your systems": "Unterbrechungsfreie Betreuung Ihrer Systeme",
"24/7/365 availability": "Verfügbarkeit 24/7/365",
"Support without breaks — nights, weekends and holidays, when downtime costs the most.": "Support ohne Unterbrechung — auch nachts, an Wochenenden und Feiertagen, wenn Ausfälle am teuersten sind.",
"Dedicated teams": "Dedizierte Teams",
"A stable team that knows your applications and processes, matched to your technology stack.": "Ein festes Team, das Ihre Anwendungen und Prozesse kennt und auf Ihren Technologie-Stack abgestimmt ist.",
"L1–L3 support tiers": "Support-Level L1–L3",
"From first line and ticket handling to deep diagnostics and enhancements — one coherent service.": "Vom First Level und Ticketing bis zur tiefen Diagnose und Weiterentwicklung — ein durchgängiger Service.",
"Proactive monitoring": "Proaktives Monitoring",
"We catch problems before users do — and act before they grow.": "Wir erkennen Probleme, bevor Nutzer sie bemerken — und reagieren, bevor sie wachsen.",
"Incident management": "Incident-Management",
"Structured incident, problem and change handling, with clear communication and escalation.": "Geordnete Bearbeitung von Incidents, Problemen und Changes, mit klarer Kommunikation und Eskalation.",
"SLA & reporting": "SLA & Reporting",
"Clear SLA commitments and regular reports — full transparency of service quality.": "Klare SLA-Zusagen und regelmäßige Berichte — volle Transparenz der Servicequalität.",
"Knowledge transfer": "Wissenstransfer",
"Managed knowledge transfer — from zero to full ownership": "Gesteuerter Wissenstransfer — von null bis zur vollen Verantwortung",
"Before we take over support, we run a structured knowledge transfer. That lets us deliver at the highest level from day one of steady state.": "Bevor wir den Support übernehmen, führen wir einen strukturierten Wissenstransfer durch. So liefern wir vom ersten Tag des Steady State an auf höchstem Niveau.",
"Discovery & documentation": "Discovery & Dokumentation",
"We learn the applications, processes and risks; we build or complete the knowledge base and runbooks.": "Wir lernen Anwendungen, Prozesse und Risiken kennen; wir erstellen oder vervollständigen die Wissensbasis und Runbooks.",
"Shadowing": "Shadowing",
"Our team learns from your experts by observing day-to-day work and real tickets.": "Unser Team lernt von Ihren Experten, indem es die tägliche Arbeit und echte Tickets beobachtet.",
"Reverse shadowing": "Reverse Shadowing",
"We take over tasks under your experts' supervision, proving the team's readiness.": "Wir übernehmen Aufgaben unter Aufsicht Ihrer Experten und stellen die Einsatzbereitschaft des Teams unter Beweis.",
"Steady state": "Steady State",
"We run the service independently and with full ownership — with continuous improvement.": "Wir erbringen den Service eigenständig und mit voller Verantwortung — mit kontinuierlicher Verbesserung.",
"World-class standards": "Weltklasse-Standards",
"We work to the best standards in the industry": "Wir arbeiten nach den besten Standards der Branche",
"Our support is built on recognised international standards for service management, security and reliability.": "Unser Support basiert auf anerkannten internationalen Standards für Servicemanagement, Sicherheit und Zuverlässigkeit.",
"IT service management": "IT-Servicemanagement",
"Best practices for incident, problem and change management — an orderly, repeatable service.": "Best Practices für Incident-, Problem- und Change-Management — ein geordneter, wiederholbarer Service.",
"IT service standard": "IT-Service-Standard",
"The international standard for IT service management — assuring quality and measurability.": "Der internationale Standard für IT-Servicemanagement — für Qualität und Messbarkeit.",
"Information security": "Informationssicherheit",
"Protecting data and systems in line with the recognised information-security standard.": "Schutz von Daten und Systemen gemäß dem anerkannten Standard für Informationssicherheit.",
"Reliability (Site Reliability)": "Zuverlässigkeit (Site Reliability)",
"SRE practices: automating operations, measurable reliability and minimising downtime.": "SRE-Praktiken: Automatisierung des Betriebs, messbare Zuverlässigkeit und Minimierung von Ausfällen.",
"Multi-timezone support": "Support über mehrere Zeitzonen",
"Teams across time zones deliver smooth, round-the-clock support without night shifts on your side.": "Teams in verschiedenen Zeitzonen sorgen für reibungslosen Rund-um-die-Uhr-Support — ohne Nachtschichten auf Ihrer Seite.",
"Measured outcomes": "Gemessene Ergebnisse",
"Availability, response and repair time (MTTR) and SLA adherence — all reported.": "Verfügbarkeit, Reaktions- und Wiederherstellungszeit (MTTR) sowie SLA-Einhaltung — alles im Reporting.",
"Benefits": "Nutzen",
"Peace of mind on continuity": "Ruhe beim Thema Betriebskontinuität",
"We take ownership of operations so your team can focus on growth, not firefighting.": "Wir übernehmen die Verantwortung für den Betrieb, damit Ihr Team sich auf Wachstum konzentrieren kann statt auf das Löschen von Bränden.",
"Faster response and repair": "Kürzere Reaktions- und Wiederherstellungszeit",
"Higher availability of critical apps": "Höhere Verfügbarkeit kritischer Anwendungen",
"Your internal IT team relieved": "Entlastung Ihres internen IT-Teams",
"Predictable cost and clear SLAs": "Planbare Kosten und klare SLAs",
"Security and compliance": "Sicherheit und Compliance",
"Have an application that can't go down?": "Haben Sie eine Anwendung, die nicht ausfallen darf?",
"We'll build it a dedicated team and 24/7 support.": "Wir bauen dafür ein dediziertes Team und 24/7-Support.",
"Robots and AI agents for repetitive processes.": "Roboter und KI-Agenten für wiederkehrende Prozesse.",
"We take over and optimise processes.": "Wir übernehmen und optimieren Prozesse.",
"24/7 support & AMS": "24/7-Support & AMS",
"24/7 support for critical applications.": "Rund-um-die-Uhr-Support für kritische Anwendungen.",
"IT and finance teams and specialists.": "IT- und Finanzteams sowie -spezialisten.",
"Dedicated products and integrations.": "Dedizierte Produkte und Integrationen.",
"Reporting & KPI analytics": "Berichte & KPI-Analysen",
"Automated reports, faster decisions.": "Automatische Berichte, schnellere Entscheidungen.",
"End-to-end support": "Umfassende Unterstützung",
"From automation and outsourcing to IT expert teams — with a best-offer guarantee.": "Von Automatisierung und Outsourcing bis zu IT-Expertenteams — mit Best-Offer-Garantie.",
"View all": "Alle ansehen",
"Driver settlement, TMS/ERP integration.": "Fahrerabrechnung, TMS/ERP-Integration.",
"10+ automations delivered — see case studies.": "10+ umgesetzte Automatisierungen — Case Studies ansehen.",
"Operations, procurement, AMS.": "Betriebs- und Einkaufsprozesse, AMS.",
"P2P/O2C, compliance, KPI reporting.": "P2P/O2C, Compliance, KPI-Reporting.",
"Back-office, app support, IT teams.": "Back-Office, Anwendungssupport, IT-Teams.",
"Supply chain, finance, IT experts.": "Lieferkette, Finanzen, IT-Experten.",
"Automated driver settlement for transport & logistics — from data to payroll.": "Automatische Fahrerabrechnung für Transport & Spedition — von Daten bis zur Lohnabrechnung.",
"Talent & IT experts": "Recruiting & IT-Experten",
"Enabling Corporate Excellence": "Enabling Corporate Excellence",
"An international partner in process automation, outsourcing and IT talent delivery.": "Internationaler Partner für Prozessautomatisierung, Outsourcing und die Bereitstellung von IT-Experten.",
"All rights reserved.": "Alle Rechte vorbehalten.",
"Enterprise-grade automation with a market leader": "Automatisierung in Enterprise-Qualität mit einem Marktführer",
"UiPath — a leader in agentic business orchestration. As a UiPath Authorized Partner we bring software robots, AI agents and people together into one coordinated process — on a secure, scalable platform.": "UiPath — ein führender Anbieter für agentic business orchestration. Als autorisierter UiPath-Partner führen wir Software-Roboter, KI-Agenten und Menschen zu einem koordinierten Prozess zusammen — auf einer sicheren, skalierbaren Plattform.",
"Agents, robots and people in one rhythm": "Agenten, Roboter und Menschen im selben Takt",
"An enterprise-grade platform — secure and scalable": "Eine Plattform in Enterprise-Qualität — sicher und skalierbar",
"From piloting to scaling across the organisation": "Vom Piloten bis zur Skalierung im gesamten Unternehmen",
"Explore automation": "Automatisierung entdecken",
"Next-generation automation orchestration.": "Automatisierungs-Orchestrierung der nächsten Generation.",
"UiPath Authorized Partner": "UiPath Autorisierter Partner",
"UiPath — a leader in agentic business orchestration. We build software robots and AI agents that work in sync with people and your systems.": "UiPath — ein führender Anbieter für agentic business orchestration. Wir bauen Software-Roboter und KI-Agenten, die im Einklang mit Menschen und Ihren Systemen arbeiten.",
"Automation on an enterprise-grade platform — secure and scalable": "Automatisierung auf einer Plattform in Enterprise-Qualität — sicher und skalierbar",
"Agents, robots and people working in one rhythm": "Agenten, Roboter und Menschen, die im selben Takt arbeiten",
"Proven rollouts — from piloting to scaling": "Bewährte Rollouts — vom Piloten bis zur Skalierung",
"About": "Über uns",
"contract retention": "Vertragsbindung",
"bn €": "Mrd. €",
"Flagship product": "Flaggschiff-Produkt",
"How we work": "Wie wir arbeiten",
"View the solution": "Lösung ansehen",
"Skip to content": "Zum Inhalt springen",

# ---- Agentic solutions section
"1": "1",
"~10 s": "~10 s",
"−70%": "−70 %",
"88% of companies are piloting or have deployed AI agents (KPMG Quarterly Pulse, 4Q 2025). The question isn't “whether” — it's “how”: safely, and with a real return.": "88 % der Unternehmen pilotieren KI-Agenten oder haben sie bereits im Einsatz (KPMG Quarterly Pulse, 4Q 2025). Die Frage ist nicht „ob“, sondern „wie“ — sicher und mit echtem Return.",
"A 30-minute demo on realistic data — no strings attached.": "Eine 30-minütige Demo auf realistischen Daten — völlig unverbindlich.",
"A 30-minute demo on your examples — we'll show where to start so the return is fast and measurable.": "Eine 30-minütige Demo an Ihren Beispielen — wir zeigen, wo man anfängt, damit der Return schnell und messbar ist.",
"A close 2–4 days shorter": "Ein um 2–4 Tage kürzerer Abschluss",
"A close that's days shorter — because someone finally watches it around the clock.": "Ein um Tage kürzerer Abschluss — weil ihn endlich jemand rund um die Uhr im Blick behält.",
"A full audit trail from question to action": "Ein lückenloser Audit-Trail von der Frage bis zur Aktion",
"A full audit trail of every answer and action": "Ein lückenloser Audit-Trail jeder Antwort und Aktion",
"AI agents that work like your best team": "KI-Agenten, die wie Ihr bestes Team arbeiten",
"Account owners get context, not homework": "Kundenbetreuer bekommen Kontext statt Hausaufgaben",
"Actions require human approval": "Aktionen erfordern menschliche Freigabe",
"Agentic AI · Case study": "Agentic AI · Case Study",
"Agentic orchestration binds agents, robots, systems and people into one safe, auditable process — instead of a collection of disconnected AI experiments.": "Agentische Orchestrierung verbindet Agenten, Roboter, Systeme und Menschen zu einem sicheren, prüfbaren Prozess — statt einer Sammlung unverbundener KI-Experimente.",
"Agentic solution case studies": "Case Studies agentischer Lösungen",
"Agentic solutions": "Agentische Lösungen",
"Agentic solutions — AI agents on Microsoft Teams": "Agentische Lösungen — KI-Agenten auf Microsoft Teams",
"Agents think": "Agenten denken",
"Agents think. Robots do. People lead.": "Agenten denken. Roboter handeln. Menschen führen.",
"Agents think. Robots do. You lead.": "Agenten denken. Roboter handeln. Sie führen.",
"Alerts before problems grow": "Alarme, bevor Probleme wachsen",
"Aligned with IT and compliance policies": "Im Einklang mit IT- und Compliance-Richtlinien",
"All agentic solutions": "Alle agentischen Lösungen",
"An AI agent available on Microsoft Teams answers board questions about finance, sales and operations in seconds. It prepares the pre-meeting brief, explains the “why”, and on your instruction triggers actions — with full control and an audit trail.": "Ein KI-Agent auf Microsoft Teams beantwortet Vorstandsfragen zu Finanzen, Vertrieb und Betrieb in Sekunden. Er bereitet den Brief vor der Sitzung vor, erklärt das „Warum“ und löst auf Ihre Anweisung Aktionen aus — mit voller Kontrolle und Audit-Trail.",
"An hour a day back per board member": "Eine Stunde pro Tag zurück — pro Vorstandsmitglied",
"Answers in seconds": "Antworten in Sekunden",
"Automatic Teams nudges to task owners": "Automatische Teams-Erinnerungen an Aufgabenverantwortliche",
"Book a demo": "Demo vereinbaren",
"Case study: the executive assistant": "Case Study: der Vorstandsassistent",
"Collection · Agentic AI": "Sammlung · Agentic AI",
"Collections runs on people's calendars: reminders go out in batches, escalations get lost in email, and the biggest debtors queue up with the smallest.": "Das Forderungsmanagement folgt den Kalendern der Menschen: Erinnerungen gehen stapelweise raus, Eskalationen versanden in E-Mails, und die größten Schuldner stehen mit den kleinsten in einer Reihe.",
"Correspondence written in context, not from a template": "Korrespondenz im Kontext geschrieben, nicht aus der Vorlage",
"Data stays inside your environment": "Daten bleiben in Ihrer Umgebung",
"Decisions faster by days, not hours": "Entscheidungen um Tage schneller, nicht um Stunden",
"Every action fully auditable": "Jede Aktion vollständig prüfbar",
"Every answer and action leaves a full audit trail. Human-in-the-loop isn't an option — it's the rule.": "Jede Antwort und Aktion hinterlässt einen lückenlosen Audit-Trail. Human-in-the-Loop ist keine Option — es ist die Regel.",
"Every morning the agent posts a concise brief in the board channel: yesterday's sales, production, cash and the exceptions that need attention. Then it answers follow-ups — like a person, only faster.": "Jeden Morgen postet der Agent einen kompakten Brief im Vorstandskanal: gestriger Umsatz, Produktion, Cash und die Ausnahmen, die Aufmerksamkeit brauchen. Danach beantwortet er Rückfragen — wie ein Mensch, nur schneller.",
"Examples based on real deployments and pilots; client details anonymised.": "Beispiele basieren auf realen Implementierungen und Piloten; Kundendaten anonymisiert.",
"Exceptions and risks surfaced before they grow": "Ausnahmen und Risiken sichtbar, bevor sie wachsen",
"Executive assistant": "Vorstandsassistent",
"Executive assistant and agents on Teams — case studies.": "Vorstandsassistent und Agenten auf Teams — Case Studies.",
"Executive assistant on Teams — see the real case study": "Vorstandsassistent auf Teams — echte Case Study ansehen",
"Executive assistant, morning brief, month-end close, receivables — see how a Teams conversation turns into finished work.": "Vorstandsassistent, Morgen-Brief, Monatsabschluss, Forderungen — sehen Sie, wie aus einem Teams-Gespräch erledigte Arbeit wird.",
"Fewer overtime hours in finance": "Weniger Überstunden im Finanzteam",
"Flagship case study": "Flaggschiff-Case-Study",
"Follow-up questions answered instantly, no analysts involved": "Rückfragen sofort beantwortet — ohne Analysten zu binden",
"From the number to the cause: which market, which client, which SKU. No dashboard spelunking.": "Von der Zahl zur Ursache: welcher Markt, welcher Kunde, welche SKU. Ohne Dashboard-Odyssee.",
"From words to action": "Von Worten zur Tat",
"Full control": "Volle Kontrolle",
"Guardrails: the agent does exactly what it should": "Guardrails: Der Agent tut genau das, was er soll",
"Human-in-the-loop": "Human-in-the-Loop",
"Human-in-the-loop: actions with human approval": "Human-in-the-Loop: Aktionen mit menschlicher Freigabe",
"Impact": "Wirkung",
"In Polish, English and German. On laptop, tablet and phone — wherever Teams is.": "Auf Polnisch, Englisch und Deutsch. Auf Laptop, Tablet und Handy — überall dort, wo Teams ist.",
"In plain language, like you'd ask a person. No forms, no SQL, no training.": "In normaler Sprache, wie bei einem Menschen. Keine Formulare, kein SQL, keine Schulung.",
"Indicative values from pilot deployments; they depend on data scope and configuration.": "Richtwerte aus Pilotimplementierungen; abhängig von Datenumfang und Konfiguration.",
"Instead of asking the team to “quickly pull the numbers” and waiting until Wednesday, you ask the question on Teams — from your laptop, or your phone on the way to the meeting.": "Statt das Team zu bitten, „schnell die Zahlen zu ziehen“, und bis Mittwoch zu warten, stellen Sie die Frage auf Teams — vom Laptop oder vom Handy auf dem Weg zur Sitzung.",
"It answers — and acts only with your approval": "Er antwortet — und handelt nur mit Ihrer Freigabe",
"It interprets the intent and sees only the data that person is entitled to.": "Er interpretiert die Absicht und sieht nur die Daten, zu denen die Person berechtigt ist.",
"It prioritises, writes, escalates and proposes decisions — you just approve.": "Er priorisiert, schreibt, eskaliert und schlägt Entscheidungen vor — Sie geben nur frei.",
"It reaches the data and orchestrates robots": "Er greift auf Daten zu und orchestriert Roboter",
"Lower DSO and fewer overdues": "Niedrigere DSO und weniger Überfälligkeiten",
"Monday reports describe last week, dashboards require digging, and the signals that matter still arrive too late.": "Montagsberichte beschreiben die Vorwoche, Dashboards erfordern Suchen — und die wichtigen Signale kommen trotzdem zu spät.",
"Monday, 7:58 am": "Montag, 7:58 Uhr",
"Month-end close is dozens of tasks, dependencies and reminders. The CFO sees status only when someone compiles it — and slippage surfaces on the last day.": "Der Monatsabschluss besteht aus Dutzenden Aufgaben, Abhängigkeiten und Erinnerungen. Der CFO sieht den Status erst, wenn ihn jemand zusammenstellt — und Verzögerungen zeigen sich am letzten Tag.",
"New": "Neu",
"No black box": "Keine Black Box",
"Numbers, trends and items for decision — ready in the board channel an hour before the meeting.": "Zahlen, Trends und Entscheidungsthemen — eine Stunde vor der Sitzung fertig im Vorstandskanal.",
"Observability: every step visible and measurable": "Observability: Jeder Schritt sichtbar und messbar",
"On your OK it triggers UiPath robots: a report, dunning, an order block. You decide — it executes.": "Auf Ihr OK startet er UiPath-Roboter: Bericht, Mahnlauf, Auftragssperre. Sie entscheiden — er führt aus.",
"One assistant. The whole company within a question's reach.": "Ein Assistent. Das ganze Unternehmen — eine Frage entfernt.",
"One brief for the whole board — a single version of the truth": "Ein Brief für den gesamten Vorstand — eine einzige Version der Wahrheit",
"P&L, cash flow, margins, DSO, sales vs plan — no waiting for a report, no “almost current” version.": "GuV, Cashflow, Margen, DSO, Umsatz vs. Plan — ohne auf einen Bericht zu warten, ohne „fast aktuelle“ Version.",
"People lead": "Menschen führen",
"Permissions and data controlled by your IT": "Berechtigungen und Daten unter Kontrolle Ihrer IT",
"Priorities by risk and value, not list order": "Prioritäten nach Risiko und Wert, nicht nach Listenreihenfolge",
"Read it": "Jetzt lesen",
"Reconciliations and posting proposals with an audit trail": "Abstimmungen und Buchungsvorschläge mit Audit-Trail",
"Robots do": "Roboter handeln",
"Role-based access — everyone sees only their data": "Rollenbasierter Zugriff — jeder sieht nur seine Daten",
"SAP, the data warehouse, BI, operational systems — with UiPath robots handling the routine work.": "SAP, Data Warehouse, BI, operative Systeme — die Routinearbeit übernehmen UiPath-Roboter.",
"Secure by design, not by declaration": "Sicher durch Design, nicht per Erklärung",
"Security and control": "Sicherheit und Kontrolle",
"See the agents in action": "Erleben Sie die Agenten in Aktion",
"See this agent live": "Erleben Sie diesen Agenten live",
"See what it looks like in practice": "Sehen Sie, wie es in der Praxis aussieht",
"Speaks your language": "Spricht Ihre Sprache",
"Talk to your company's data like your best analyst: answers in seconds, a pre-meeting brief, actions on your OK.": "Sprechen Sie mit den Daten Ihres Unternehmens wie mit Ihrem besten Analysten: Antworten in Sekunden, ein Brief vor der Sitzung, Aktionen auf Ihr OK.",
"Teams escalations to the right people, instantly": "Teams-Eskalationen an die richtigen Personen — sofort",
"The CFO sees status at any moment": "Der CFO sieht den Status jederzeit",
"The agent analyses receivables continuously, writes personalised reminders tuned to the client and history, escalates on Teams to the right people, and proposes decisions — like order blocks — executing them once approved.": "Der Agent analysiert Forderungen laufend, schreibt personalisierte, auf Kunde und Historie abgestimmte Erinnerungen, eskaliert auf Teams an die richtigen Personen und schlägt Entscheidungen vor — etwa Auftragssperren — und führt sie nach Freigabe aus.",
"The agent runs the close checklist 24/7: watches deadlines, nudges task owners on Teams, reconciles items and proposes postings, and drafts the first version of the management commentary on variances.": "Der Agent führt die Abschluss-Checkliste 24/7: überwacht Termine, erinnert Aufgabenverantwortliche auf Teams, stimmt Positionen ab, schlägt Buchungen vor und entwirft die erste Version des Management-Kommentars zu Abweichungen.",
"The agent understands and checks permissions": "Der Agent versteht und prüft Berechtigungen",
"The agentic approach": "Der agentische Ansatz",
"The assistant understands the question, reaches into SAP, the data warehouse and operational systems, and answers like your best analyst: with the number, the context and a recommendation. This isn't a vision — it's a deployment our clients use every day.": "Der Assistent versteht die Frage, greift auf SAP, Data Warehouse und operative Systeme zu und antwortet wie Ihr bester Analyst: mit der Zahl, dem Kontext und einer Empfehlung. Das ist keine Vision — sondern eine Implementierung, die unsere Kunden täglich nutzen.",
"The board gets speed — security gets control. The solution runs within UiPath agentic orchestration: with guardrails, observability and human oversight.": "Der Vorstand bekommt Geschwindigkeit — die Sicherheit bekommt Kontrolle. Die Lösung läuft in der agentischen Orchestrierung von UiPath: mit Guardrails, Observability und menschlicher Aufsicht.",
"The board meets in two hours. You already know everything.": "Die Sitzung ist in zwei Stunden. Sie wissen schon alles.",
"The board starts the day with the full picture — before anyone has to ask for it.": "Der Vorstand startet mit dem vollständigen Bild in den Tag — bevor jemand danach fragen muss.",
"The close checklist watched 24/7": "Die Abschluss-Checkliste rund um die Uhr im Blick",
"The end of “we didn't know”": "Das Ende von „das wussten wir nicht“",
"The executive assistant on Microsoft Teams": "Der Vorstandsassistent auf Microsoft Teams",
"The executive assistant: talk to your company's data the way you talk to people": "Der Vorstandsassistent: Sprechen Sie mit Ihren Unternehmensdaten wie mit Menschen",
"The first draft of management commentary writes itself": "Die erste Fassung des Management-Kommentars schreibt sich selbst",
"The full day's picture in a 90-second read": "Das komplette Tagesbild in 90 Sekunden Lektüre",
"The month-end close agent": "Der Monatsabschluss-Agent",
"The morning executive brief, daily at 7:00": "Der Morgen-Brief für den Vorstand, täglich um 7:00",
"The pre-meeting brief": "Der Brief vor der Sitzung",
"The receivables agent: cash comes back sooner": "Der Forderungs-Agent: Das Geld kommt schneller zurück",
"The “why” drill-down": "Der „Warum“-Drill-down",
"They decide wherever judgement is needed. Every agent action waits for their approval.": "Sie entscheiden überall dort, wo Urteilsvermögen gefragt ist. Jede Aktion des Agenten wartet auf ihre Freigabe.",
"They execute tasks in SAP and other systems precisely — repeatably, fast and 24/7.": "Sie führen Aufgaben in SAP und anderen Systemen präzise aus — wiederholbar, schnell und 24/7.",
"They understand context and unstructured data, plan next steps and know when to ask a human.": "Sie verstehen Kontext und unstrukturierte Daten, planen nächste Schritte und wissen, wann sie einen Menschen fragen müssen.",
"Want an assistant like this for your board?": "Möchten Sie so einen Assistenten für Ihren Vorstand?",
"Watches your KPIs and speaks up when something drifts off course — diagnosis included.": "Überwacht Ihre KPIs und meldet sich, wenn etwas vom Kurs abkommt — Diagnose inklusive.",
"We deploy agents within UiPath orchestration — with the same security standards we apply in automations for market leaders.": "Wir implementieren Agenten innerhalb der UiPath-Orchestrierung — mit denselben Sicherheitsstandards wie in unseren Automatisierungen für Marktführer.",
"We'll show it live on realistic demo data — 30 minutes, no strings attached.": "Wir zeigen ihn live auf realistischen Demo-Daten — 30 Minuten, völlig unverbindlich.",
"What it can do": "Was er kann",
"What the agent does": "Was der Agent tut",
"What the board gains": "Was der Vorstand gewinnt",
"Why boards buy this": "Warum Vorstände das kaufen",
"Works 24/7 — including while the team sleeps": "Arbeitet 24/7 — auch dann, wenn das Team schläft",
"You ask a question on Microsoft Teams. The agent understands, reaches the data and triggers UiPath robots — and you get the answer and the finished work. With permissions, guardrails and a full audit trail.": "Sie stellen eine Frage auf Microsoft Teams. Der Agent versteht sie, greift auf die Daten zu und startet UiPath-Roboter — und Sie erhalten die Antwort und die erledigte Arbeit. Mit Berechtigungen, Guardrails und lückenlosem Audit-Trail.",
"You ask on Teams": "Sie fragen auf Teams",
"ad-hoc requests to the FP&A team": "Ad-hoc-Anfragen an das FP&A-Team",
"available 24/7, phone included": "verfügbar 24/7, auch mobil",
"average time to answer a board question": "durchschnittliche Antwortzeit auf eine Vorstandsfrage",
"version of the truth — everyone sees the same numbers": "Version der Wahrheit — alle sehen dieselben Zahlen",
}

DE_TITLE_BY_EN = {
"Mientha — Enabling Corporate Excellence": "Mientha — Enabling Corporate Excellence",
"Services — Mientha": "Leistungen — Mientha",
"Industries — Mientha": "Branchen — Mientha",
"Driver settlement — Mientha": "Fahrerabrechnung — Mientha",
"Case studies — Mientha": "Case Studies — Mientha",
"About — Mientha": "Über uns — Mientha",
"Contact — Mientha": "Kontakt — Mientha",
"Automated VAT settlements — Mientha": "Automatische MwSt-Abrechnungen — Mientha",
"Collections cases routed to the right person instantly — Mientha": "Inkassofälle gehen sofort an die richtige Person — Mientha",
"Faster release of blocked orders — Mientha": "Schnellere Freigabe gesperrter Aufträge — Mientha",
"Smooth payment-term changes — Mientha": "Reibungslose Änderung von Zahlungszielen — Mientha",
"Fast, consistent credit decisions — Mientha": "Schnelle und konsistente Kreditentscheidungen — Mientha",
"Automated P2P query handling — Mientha": "Automatische Bearbeitung von P2P-Anfragen — Mientha",
"Bank-statement monitoring & cash application — Mientha": "Überwachung von Kontoauszügen & Cash Application — Mientha",
"Automated bank-balance reconciliation — Mientha": "Automatischer Abgleich von Bankkontosalden — Mientha",
"Employee data mass update — Mientha": "Massenaktualisierung von Mitarbeiterdaten — Mientha",
"Automated new-hire onboarding — Mientha": "Automatisches Onboarding neuer Mitarbeiter — Mientha",
"FMCG — automation case studies — Mientha": "FMCG — Automatisierungs-Case-Studies — Mientha",
"24/7 application support — Mientha": "24/7-Anwendungssupport — Mientha",
"Agentic solutions — Mientha": "Agentische Lösungen — Mientha",
"Executive assistant on Teams — Mientha": "Vorstandsassistent auf Teams — Mientha",
"The morning executive brief, daily at 7:00 — Mientha": "Der Morgen-Brief für den Vorstand — Mientha",
"The month-end close agent — Mientha": "Der Monatsabschluss-Agent — Mientha",
"The receivables agent: cash comes back sooner — Mientha": "Der Forderungs-Agent — Mientha",
}
